# Generated by Django 2.2.5 on 2019-12-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, verbose_name='名前')),
                ('email', models.EmailField(max_length=254, verbose_name='会社メールアドレス')),
                ('avatar', models.ImageField(upload_to='avatar/', verbose_name='写真')),
                ('desire', models.ImageField(upload_to='avatar/', verbose_name='願望')),
            ],
            options={
                'verbose_name': '願望',
                'verbose_name_plural': '願望一覧',
                'db_table': 'mst_desire',
            },
        ),
    ]
