# Generated by Django 2.2.5 on 2019-12-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desire',
            name='desire',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='願望'),
        ),
    ]
